magephp:
  log_dir: ./deploy-log
  log_limit: 10
#  composer:
#    path: /alternative/path-to/composer.phar
  environments:
    production:
#      composer:
#        path: /usr/bin/composer
      user: u86000088
      branch: master
      from: ./
      host_path: pagenode.bistro-grammophon.de
      releases: 3
      hosts:
        - home642369041.1and1-data.host
      ssh:
        port: 22
        flags: -v -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa
      exclude:
        - ._*
        - ./deploy-log
        - .DS_Store
        - .idea
        - .ddev
        - Makefile
        - .gitignore
        - composer.*
        - .mage.yml
        - ./Notes*.md
        - ./Readme*.md
        - ./bin

      # local -> e.g. Pulling from repository, switching branches, installing vendors
      pre-deploy:
#        - git/update
#        - git/change-branch develop
#        - composer/self-update
        - composer/install: { flags: '--no-dev'}
        - composer/dump-autoload
      
      # remote -> e.g. Warming cache, installing assets, switching configuration
      on-deploy:
#        - fs/link: { from: '../../../../www.bistro-grammophon.de/fileadmin', to: 'public/fileadmin' }
#        - fs/link: { from: '../../../../www.bistro-grammophon.de/uploads', to: 'public/uploads' }
#        - fs/link: { from: '../../../../www.bistro-grammophon.de/typo3temp', to: 'public/typo3temp' }
#        - symfony/cache-warmup: { env: 'dev' }
#        - symfony/assets-install: { env: 'dev' }
#        - fs/copy: { from: '../../../shared/images', to: 'web/images', flags: {} }
#        - fs/link: { from: '../../../shared/images', to: 'web/images', flags: {} }
#        - fs/move: { from: '../../../shared/images', to: 'web/images', flags: {} }
#        - fs/remove: { file: '../../../shared/images', flags: {} }
#        - fs/chmod: { file: /foo/bar, mode: '755', flags: {} }
      
      # remote -> e.g. Puring APC Cache
      on-release:
      
      # remote -> e.g. Removing locks, purging cache
      post-release:

      # local -> e.g. Purging cache
      post-deploy:
        - composer/install: { flags: ''}
#        - exec: { cmd: './reload-docker.sh', desc: 'Reload Docker instances' }
